name: Build Aplikasi Otomatis

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4 # Update ke v4 (terbaru)
    
    - name: Set up Python
      uses: actions/setup-python@v5 # Update ke v5 (terbaru)
      with:
        python-version: '3.11' # Gunakan versi Python yang lebih modern
        
    - name: Install Library
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl Pillow pyinstaller
        
    - name: Mulai Membuat EXE (Build)
      run: |
        # PERBAIKAN PENTING 1: Menambahkan folder "CVMS/" sebelum nama file
        pyinstaller --onefile --noconsole --name "AplikasiSuratBNI" CVMS/AplikasiSuratBNI.py
        
    - name: Upload Hasil Jadi
      # PERBAIKAN PENTING 2: Mengganti v3 menjadi v4 (Solusi error screenshotmu)
      uses: actions/upload-artifact@v4
      with:
        name: AplikasiSuratBNI-Windows
        path: dist/AplikasiSuratBNI.exe
