name: Buat Aplikasi Windows

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # DISINI KITA TAMBAH XLRD BIAR BISA BACA EXCEL LAMA
    - name: Install Dependencies
      run: |
        pip install pandas openpyxl pyinstaller pywin32 xlrd

    - name: Bikin Jadi EXE (PyInstaller)
      run: |
        # Pastikan path CVMS/AplikasiSuratBNI.py sesuai dengan struktur foldermu
        pyinstaller --noconsole --onefile --windowed --name "SuratBNI_Ultimate" CVMS/AplikasiSuratBNI.py

    - name: Upload Hasilnya
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Surat-Ultimate
        path: dist/SuratBNI_Ultimate.exe
